### ISSUE TITLE
Support for 1.18+?

### ISSUE THREAD

**Issue by Godly000** [andpenguin/AAFSG#1]
Since overworlds were shuffled in 1.18, would it be possible to include a seed finder for 1.18+?

**Comment by andpenguin** [comment]
The seedfinding libraries I used are only updated to 1.17.2. It would be possible to make a filter for 1.18+, but honestly I don't really feel like it because its a lot of work for an idea I've already done.

**Comment by Godly000** [comment]
And you are trying to fix the website being down right now, right?
